### ISSUE TITLE
Problem with gopro camera

### ISSUE THREAD

**Issue by xeurito** [sasseries/iw4-cine-mod#2]
Whenever I turn the gopro mode on, all the closest objects doesn't appear or they are cut. Is that normal and if it's not when will this be fixed ?

**Comment by sasseries** [comment]
This issue is due to one of the functions (**_CameraLinkTo();_**) that disconnects the camera from the player entity. This is used originally on player-controlled killstreaks where draw distance of close objects isn't an issue.

This won't be worked on as it is an engine related issue. For the "GoPro" command, I suggest placing the camera fairly far and use a tight field of view (cg_fov) to get a closer look to your subject.
